“WEAPON_KNIFE” (http://gta.wikia.com/wiki/Knife 5.2k)
“WEAPON_KNUCKLE” (http://gta.wikia.com/wiki/Brass_Knuckles 2.9k)
“WEAPON_NIGHTSTICK” (http://gta.wikia.com/wiki/Nightstick 1.9k)
“WEAPON_HAMMER” (http://gta.wikia.com/wiki/Hammer 1.4k)
“WEAPON_BAT” (http://gta.wikia.com/wiki/Bat 1.6k)
“WEAPON_GOLFCLUB” (http://gta.wikia.com/wiki/Baseball_Bat 798)
“WEAPON_CROWBAR” (http://gta.wikia.com/wiki/Crowbar 1.4k)
“WEAPON_BOTTLE” (http://gta.wikia.com/wiki/Broken_Bottle 913)
“WEAPON_DAGGER” (http://gta.wikia.com/wiki/Antique_Cavalry_Dagger 1.7k)
“WEAPON_HATCHET” (http://gta.wikia.com/wiki/Hatchet 1.4k)
“WEAPON_MACHETE” (http://gta.wikia.com/wiki/Machete 757)
“WEAPON_FLASHLIGHT” (http://gta.wikia.com/wiki/Flashlight 1.0k)
“WEAPON_SWITCHBLADE” (http://gta.wikia.com/wiki/Switchblade 1.9k)
“WEAPON_PROXMINE” (http://gta.wikia.com/wiki/Proximity_Mines 1.3k)
“WEAPON_BZGAS” (http://gta.wikia.com/wiki/BZ_Gas 1.3k)
“WEAPON_SMOKEGRENADE” (http://gta.wikia.com/wiki/Tear_Gas 651)
“WEAPON_MOLOTOV” (http://gta.wikia.com/wiki/Molotov_Cocktails 564)
“WEAPON_FIREEXTINGUISHER” (http://gta.wikia.com/wiki/Fire_Extinguisher 1.3k)
“WEAPON_PETROLCAN” (http://gta.wikia.com/wiki/Jerry_Can 1.2k)
“WEAPON_HAZARDCAN” (###)
“WEAPON_SNOWBALL” (http://gta.wikia.com/wiki/Snowballs 581)
“WEAPON_FLARE” (http://gta.wikia.com/wiki/Flare 1.0k)
“WEAPON_BALL” (http://gta.wikia.com/wiki/Ball 800)
“WEAPON_REVOLVER” (http://gta.wikia.com/wiki/Heavy_Revolver 1.7k)
“WEAPON_POOLCUE” (http://gta.wikia.com/wiki/Pool_Cue 1.8k)
“WEAPON_PIPEWRENCH” (http://gta.wikia.com/wiki/Pipe_Wrench 1.6k)
“WEAPON_PISTOL” (http://gta.wikia.com/wiki/Pistol 2.1k)
“WEAPON_PISTOL_MK2” (http://gta.wikia.com/wiki/Pistol_Mk_II 2.2k)
“WEAPON_COMBATPISTOL” (http://gta.wikia.com/wiki/Combat_Pistol 1.5k)
“WEAPON_APPISTOL” (http://gta.wikia.com/wiki/AP_Pistol 1.7k)
“WEAPON_PISTOL50” (http://gta.wikia.com/wiki/Desert_Eagle 1.7k)
“WEAPON_SNSPISTOL” (http://gta.wikia.com/wiki/SNS_Pistol 1.6k)
“WEAPON_HEAVYPISTOL” (http://gta.wikia.com/wiki/Heavy_Pistol 1.6k)
“WEAPON_VINTAGEPISTOL” (http://gta.wikia.com/wiki/Vintage_Pistol 1.2k)
“WEAPON_STUNGUN” (http://gta.wikia.com/wiki/Stun_Gun 1.5k)
“WEAPON_FLAREGUN” (http://gta.wikia.com/wiki/Flare_Gun 858)
“WEAPON_MARKSMANPISTOL” (http://gta.wikia.com/wiki/Marksman_Pistol 1.6k)
“WEAPON_MICROSMG” (http://gta.wikia.com/wiki/Micro_SMG 1.8k)
“WEAPON_MINISMG” (https://gta.fandom.com/wiki/Mini_SMG 117)
"WEAPON_SMG (http://gta.wikia.com/wiki/MP5 1.9k)
“WEAPON_SMG_MK2” (http://gta.wikia.com/wiki/SMG_Mk_II 1.6k)
“WEAPON_ASSAULTSMG” (http://gta.wikia.com/wiki/Assault_SMG 1.8k)
“WEAPON_MG” (http://gta.wikia.com/wiki/MG 1.4k)
“WEAPON_COMBATMG” (http://gta.wikia.com/wiki/Combat_MG 1.3k)
“WEAPON_COMBATMG_MK2” (http://gta.wikia.com/wiki/Combat_MG_Mk_II 1.2k)
“WEAPON_COMBATPDW” (http://gta.wikia.com/wiki/Combat_PDW 1.2k)
“WEAPON_GUSENBERG” (http://gta.wikia.com/wiki/Gusenberg_Sweeper 1.3k)
“WEAPON_MACHINEPISTOL” (http://gta.wikia.com/wiki/Tec-9 1.2k)
“WEAPON_ASSAULTRIFLE” (http://gta.wikia.com/wiki/AK-47 2.1k)
“WEAPON_ASSAULTRIFLE_MK2” (http://gta.wikia.com/wiki/Assault_Rifle_Mk_II 1.5k)
“WEAPON_CARBINERIFLE” (http://gta.wikia.com/wiki/Carbine_Rifle 1.7k)
“WEAPON_CARBINERIFLE_MK2” (http://gta.wikia.com/wiki/Carbine_Rifle_Mk_II 1.5k)
“WEAPON_ADVANCEDRIFLE” (http://gta.wikia.com/wiki/Advanced_Rifle 1.5k)
“WEAPON_SPECIALCARBINE” (http://gta.wikia.com/wiki/Special_Carbine 1.3k)
“WEAPON_BULLPUPRIFLE” (http://gta.wikia.com/wiki/Bullpup_Rifle 1.0k)
“WEAPON_COMPACTRIFLE” (http://gta.wikia.com/wiki/Compact_Rifle 1.1k)
“WEAPON_PUMPSHOTGUN” (http://gta.wikia.com/wiki/Pump_Shotgun 1.0k)
“WEAPON_SWEEPERSHOTGUN” http://gta.wikia.com/wiki/Sweeper_Shotgun 1.1k)
“WEAPON_SAWNOFFSHOTGUN” (http://gta.wikia.com/wiki/Sawed-Off_Shotgun 1.0k)
“WEAPON_BULLPUPSHOTGUN” (http://gta.wikia.com/wiki/Bullpup_Shotgun 744)
“WEAPON_ASSAULTSHOTGUN” (http://gta.wikia.com/wiki/Assault_Shotgun 914)
“WEAPON_MUSKET” (http://gta.wikia.com/wiki/Musket 903)
“WEAPON_HEAVYSHOTGUN” (http://gta.wikia.com/wiki/Heavy_Shotgun 767)
“WEAPON_DBSHOTGUN” (http://gta.wikia.com/wiki/Double_Barrel_Shotgun 1.2k)
“WEAPON_SNIPERRIFLE” (http://gta.wikia.com/wiki/Sniper_Rifle 933)
“WEAPON_HEAVYSNIPER” (http://gta.wikia.com/wiki/Heavy_Sniper 781)
“WEAPON_HEAVYSNIPER_MK2” (http://gta.wikia.com/wiki/Heavy_Sniper_Mk_II 877)
“WEAPON_MARKSMANRIFLE” (http://gta.wikia.com/wiki/Marksman_Rifle 799)
“WEAPON_GRENADELAUNCHER” (http://gta.wikia.com/wiki/Grenade_Launcher 578)
“WEAPON_GRENADELAUNCHER_SMOKE” (###)
“WEAPON_RPG” (http://gta.wikia.com/wiki/Rocket_Launcher 732)
“WEAPON_MINIGUN” (http://gta.wikia.com/wiki/Minigun 616)
“WEAPON_FIREWORK” (http://gta.wikia.com/wiki/Fireworks 935)
“WEAPON_RAILGUN” (http://gta.wikia.com/wiki/Railgun 1.0k)
“WEAPON_HOMINGLAUNCHER” (http://gta.wikia.com/wiki/Homing_Launcher 1.0k)
“WEAPON_GRENADE” (http://gta.wikia.com/wiki/Grenades 387)
“WEAPON_STICKYBOMB” (http://www.ign.com/wikis/gta-5/Sticky_Bomb 675)
“WEAPON_COMPACTLAUNCHER” (http://gta.wikia.com/wiki/Compact_Grenade_Launcher 821)
“WEAPON_SNSPISTOL_MK2” (http://gta.wikia.com/wiki/SNS_Pistol_Mk_II 969)
“WEAPON_REVOLVER_MK2” (http://gta.wikia.com/wiki/Heavy_Revolver_Mk_II 1.0k)
“WEAPON_DOUBLEACTION” (http://gta.wikia.com/wiki/Double-Action_Revolver 1.3k)
“WEAPON_SPECIALCARBINE_MK2” (http://gta.wikia.com/wiki/Special_Carbine_Mk_II 1.1k)
“WEAPON_BULLPUPRIFLE_MK2” (http://gta.wikia.com/wiki/Bullpup_Rifle_Mk_II 935)
“WEAPON_PUMPSHOTGUN_MK2” (http://gta.wikia.com/wiki/Pump_Shotgun_Mk_II 1.1k)
“WEAPON_MARKSMANRIFLE_MK2” (http://gta.wikia.com/wiki/Marksman_Rifle_Mk_II 2.1k)
“WEAPON_RAYPISTOL” (https://gta.fandom.com/wiki/Up-n-Atomizer 113)
“WEAPON_RAYCARBINE” (https://gta.fandom.com/wiki/Unholy_Hellbringer 74)
“WEAPON_RAYMINIGUN” (https://gta.fandom.com/wiki/Widowmaker 50)
“WEAPON_DIGISCANNER” (https://gta.fandom.com/wiki/Digiscanner 3.3k)
“WEAPON_NAVYREVOLVER” (https://gta.fandom.com/wiki/Navy_Revolver 90)
“WEAPON_CERAMICPISTOL” (https://gta.fandom.com/wiki/Ceramic_Pistol 91)
“WEAPON_STONE_HATCHET” (https://gta.fandom.com/wiki/Stone_Hatchet 76)
“WEAPON_PIPEBOMB” (https://gta.fandom.com/wiki/Pipe_Bomb 111)
“GADGET_PARACHUTE” (https://gta.fandom.com/wiki/Parachute 137)

--[[
DO NOT REMOVE BELOW

This script was fully created and developed by "Sean" there discord is "Sean B.#0899"
if you need any help with the script please contact me on my discord and I will try to
help as many of you as possibe.
]]